# frozen_string_literal: true

module Vapi
  module Types
    module InworldVoiceVoiceId
      extend Vapi::Internal::Types::Enum

      ALEX = "Alex"
      ASHLEY = "Ashley"
      CRAIG = "Craig"
      DEBORAH = "Deborah"
      DENNIS = "Dennis"
      EDWARD = "Edward"
      ELIZABETH = "Elizabeth"
      HADES = "Hades"
      JULIA = "Julia"
      PIXIE = "Pixie"
      MARK = "Mark"
      OLIVIA = "Olivia"
      PRIYA = "Priya"
      RONALD = "Ronald"
      SARAH = "Sarah"
      SHAUN = "Shaun"
      THEODORE = "Theodore"
      TIMOTHY = "Timothy"
      WENDY = "Wendy"
      DOMINUS = "Dominus"
      HANA = "Hana"
      CLIVE = "Clive"
      CARTER = "Carter"
      BLAKE = "Blake"
      LUNA = "Luna"
      YICHEN = "Yichen"
      XIAOYIN = "Xiaoyin"
      XINYI = "Xinyi"
      JING = "Jing"
      ERIK = "Erik"
      KATRIEN = "Katrien"
      LENNART = "Lennart"
      LORE = "Lore"
      ALAIN = "Alain"
      HELENE = "Hélène"
      MATHIEU = "Mathieu"
      ETIENNE = "Étienne"
      JOHANNA = "Johanna"
      JOSEF = "Josef"
      GIANNI = "Gianni"
      ORIETTA = "Orietta"
      ASUKA = "Asuka"
      SATOSHI = "Satoshi"
      HYUNWOO = "Hyunwoo"
      MINJI = "Minji"
      SEOJUN = "Seojun"
      YOONA = "Yoona"
      SZYMON = "Szymon"
      WOJCIECH = "Wojciech"
      HEITOR = "Heitor"
      MAITE = "Maitê"
      DIEGO = "Diego"
      LUPITA = "Lupita"
      MIGUEL = "Miguel"
      RAFAEL = "Rafael"
      SVETLANA = "Svetlana"
      ELENA = "Elena"
      DMITRY = "Dmitry"
      NIKOLAI = "Nikolai"
      RIYA = "Riya"
      MANOJ = "Manoj"
      YAEL = "Yael"
      OREN = "Oren"
      NOUR = "Nour"
      OMAR = "Omar"
    end
  end
end
