# frozen_string_literal: true

module Vapi
  module Types
    module RimeAiVoiceIdEnum
      extend Vapi::Internal::Types::Enum

      COVE = "cove"
      MOON = "moon"
      WILDFLOWER = "wildflower"
      EVA = "eva"
      AMBER = "amber"
      MAYA = "maya"
      LAGOON = "lagoon"
      BREEZE = "breeze"
      HELEN = "helen"
      JOY = "joy"
      MARSH = "marsh"
      CREEK = "creek"
      CEDAR = "cedar"
      ALPINE = "alpine"
      SUMMIT = "summit"
      NICHOLAS = "nicholas"
      TYLER = "tyler"
      COLIN = "colin"
      HANK = "hank"
      THUNDER = "thunder"
      ASTRA = "astra"
      EUCALYPTUS = "eucalyptus"
      MORAINE = "moraine"
      PEAK = "peak"
      TUNDRA = "tundra"
      MESA_EXTRA = "mesa_extra"
      TALON = "talon"
      MARLU = "marlu"
      GLACIER = "glacier"
      FALCON = "falcon"
      LUNA = "luna"
      CELESTE = "celeste"
      ESTELLE = "estelle"
      ANDROMEDA = "andromeda"
      ESTHER = "esther"
      LYRA = "lyra"
      LINTEL = "lintel"
      OCULUS = "oculus"
      VESPERA = "vespera"
      TRANSOM = "transom"
      BOND = "bond"
      ARCADE = "arcade"
      ATRIUM = "atrium"
      CUPOLA = "cupola"
      FERN = "fern"
      SIRIUS = "sirius"
      ORION = "orion"
      MASONRY = "masonry"
      ALBION = "albion"
      PARAPET = "parapet"
    end
  end
end
