# frozen_string_literal: true

module Vapi
  module Types
    module SpeechmaticsTranscriberLanguage
      extend Vapi::Internal::Types::Enum

      AUTO = "auto"
      AR = "ar"
      AR_EN = "ar_en"
      BA = "ba"
      EU = "eu"
      BE = "be"
      BN = "bn"
      BG = "bg"
      YUE = "yue"
      CA = "ca"
      HR = "hr"
      CS = "cs"
      DA = "da"
      NL = "nl"
      EN = "en"
      EO = "eo"
      ET = "et"
      FI = "fi"
      FR = "fr"
      GL = "gl"
      DE = "de"
      EL = "el"
      HE = "he"
      HI = "hi"
      HU = "hu"
      ID = "id"
      IA = "ia"
      GA = "ga"
      IT = "it"
      JA = "ja"
      KO = "ko"
      LV = "lv"
      LT = "lt"
      MS = "ms"
      EN_MS = "en_ms"
      MT = "mt"
      CMN = "cmn"
      CMN_EN = "cmn_en"
      MR = "mr"
      MN = "mn"
      NO = "no"
      FA = "fa"
      PL = "pl"
      PT = "pt"
      RO = "ro"
      RU = "ru"
      SK = "sk"
      SL = "sl"
      ES = "es"
      EN_ES = "en_es"
      SW = "sw"
      SV = "sv"
      TL = "tl"
      TA = "ta"
      EN_TA = "en_ta"
      TH = "th"
      TR = "tr"
      UK = "uk"
      UR = "ur"
      UG = "ug"
      VI = "vi"
      CY = "cy"
    end
  end
end
