# frozen_string_literal: true

require_relative "create_assistant_dto"
require_relative "assistant_overrides"
require_relative "chat_input"
require_relative "chat_messages_item"
require_relative "chat_output_item"
require "date"
require_relative "chat_costs_item"
require "ostruct"
require "json"

module Vapi
  class Chat
    # @return [String] This is the assistant that will be used for the chat. To use an existing
    #  assistant, use `assistantId` instead.
    attr_reader :assistant_id
    # @return [Vapi::CreateAssistantDto] This is the assistant that will be used for the chat. To use an existing
    #  assistant, use `assistantId` instead.
    attr_reader :assistant
    # @return [Vapi::AssistantOverrides] These are the variable values that will be used to replace template variables in
    #  the assistant messages.
    #  Only variable substitution is supported in chat contexts - other assistant
    #  properties cannot be overridden.
    attr_reader :assistant_overrides
    # @return [String] This is the name of the chat. This is just for your own reference.
    attr_reader :name
    # @return [String] This is the ID of the session that will be used for the chat.
    #  Mutually exclusive with previousChatId.
    attr_reader :session_id
    # @return [Vapi::ChatInput] This is the input text for the chat.
    #  Can be a string or an array of chat messages.
    attr_reader :input
    # @return [Boolean] This is a flag that determines whether the response should be streamed.
    #  When true, the response will be sent as chunks of text.
    attr_reader :stream
    # @return [String] This is the ID of the chat that will be used as context for the new chat.
    #  The messages from the previous chat will be used as context.
    #  Mutually exclusive with sessionId.
    attr_reader :previous_chat_id
    # @return [String] This is the unique identifier for the chat.
    attr_reader :id
    # @return [String] This is the unique identifier for the org that this chat belongs to.
    attr_reader :org_id
    # @return [Array<Vapi::ChatMessagesItem>] This is an array of messages used as context for the chat.
    #  Used to provide message history for multi-turn conversations.
    attr_reader :messages
    # @return [Array<Vapi::ChatOutputItem>] This is the output messages generated by the system in response to the input.
    attr_reader :output
    # @return [DateTime] This is the ISO 8601 date-time string of when the chat was created.
    attr_reader :created_at
    # @return [DateTime] This is the ISO 8601 date-time string of when the chat was last updated.
    attr_reader :updated_at
    # @return [Array<Vapi::ChatCostsItem>] These are the costs of individual components of the chat in USD.
    attr_reader :costs
    # @return [Float] This is the cost of the chat in USD.
    attr_reader :cost
    # @return [OpenStruct] Additional properties unmapped to the current class definition
    attr_reader :additional_properties
    # @return [Object]
    attr_reader :_field_set
    protected :_field_set

    OMIT = Object.new

    # @param assistant_id [String] This is the assistant that will be used for the chat. To use an existing
    #  assistant, use `assistantId` instead.
    # @param assistant [Vapi::CreateAssistantDto] This is the assistant that will be used for the chat. To use an existing
    #  assistant, use `assistantId` instead.
    # @param assistant_overrides [Vapi::AssistantOverrides] These are the variable values that will be used to replace template variables in
    #  the assistant messages.
    #  Only variable substitution is supported in chat contexts - other assistant
    #  properties cannot be overridden.
    # @param name [String] This is the name of the chat. This is just for your own reference.
    # @param session_id [String] This is the ID of the session that will be used for the chat.
    #  Mutually exclusive with previousChatId.
    # @param input [Vapi::ChatInput] This is the input text for the chat.
    #  Can be a string or an array of chat messages.
    # @param stream [Boolean] This is a flag that determines whether the response should be streamed.
    #  When true, the response will be sent as chunks of text.
    # @param previous_chat_id [String] This is the ID of the chat that will be used as context for the new chat.
    #  The messages from the previous chat will be used as context.
    #  Mutually exclusive with sessionId.
    # @param id [String] This is the unique identifier for the chat.
    # @param org_id [String] This is the unique identifier for the org that this chat belongs to.
    # @param messages [Array<Vapi::ChatMessagesItem>] This is an array of messages used as context for the chat.
    #  Used to provide message history for multi-turn conversations.
    # @param output [Array<Vapi::ChatOutputItem>] This is the output messages generated by the system in response to the input.
    # @param created_at [DateTime] This is the ISO 8601 date-time string of when the chat was created.
    # @param updated_at [DateTime] This is the ISO 8601 date-time string of when the chat was last updated.
    # @param costs [Array<Vapi::ChatCostsItem>] These are the costs of individual components of the chat in USD.
    # @param cost [Float] This is the cost of the chat in USD.
    # @param additional_properties [OpenStruct] Additional properties unmapped to the current class definition
    # @return [Vapi::Chat]
    def initialize(id:, org_id:, created_at:, updated_at:, assistant_id: OMIT, assistant: OMIT, assistant_overrides: OMIT, name: OMIT, session_id: OMIT,
                   input: OMIT, stream: OMIT, previous_chat_id: OMIT, messages: OMIT, output: OMIT, costs: OMIT, cost: OMIT, additional_properties: nil)
      @assistant_id = assistant_id if assistant_id != OMIT
      @assistant = assistant if assistant != OMIT
      @assistant_overrides = assistant_overrides if assistant_overrides != OMIT
      @name = name if name != OMIT
      @session_id = session_id if session_id != OMIT
      @input = input if input != OMIT
      @stream = stream if stream != OMIT
      @previous_chat_id = previous_chat_id if previous_chat_id != OMIT
      @id = id
      @org_id = org_id
      @messages = messages if messages != OMIT
      @output = output if output != OMIT
      @created_at = created_at
      @updated_at = updated_at
      @costs = costs if costs != OMIT
      @cost = cost if cost != OMIT
      @additional_properties = additional_properties
      @_field_set = {
        "assistantId": assistant_id,
        "assistant": assistant,
        "assistantOverrides": assistant_overrides,
        "name": name,
        "sessionId": session_id,
        "input": input,
        "stream": stream,
        "previousChatId": previous_chat_id,
        "id": id,
        "orgId": org_id,
        "messages": messages,
        "output": output,
        "createdAt": created_at,
        "updatedAt": updated_at,
        "costs": costs,
        "cost": cost
      }.reject do |_k, v|
        v == OMIT
      end
    end

    # Deserialize a JSON object to an instance of Chat
    #
    # @param json_object [String]
    # @return [Vapi::Chat]
    def self.from_json(json_object:)
      struct = JSON.parse(json_object, object_class: OpenStruct)
      parsed_json = JSON.parse(json_object)
      assistant_id = parsed_json["assistantId"]
      if parsed_json["assistant"].nil?
        assistant = nil
      else
        assistant = parsed_json["assistant"].to_json
        assistant = Vapi::CreateAssistantDto.from_json(json_object: assistant)
      end
      if parsed_json["assistantOverrides"].nil?
        assistant_overrides = nil
      else
        assistant_overrides = parsed_json["assistantOverrides"].to_json
        assistant_overrides = Vapi::AssistantOverrides.from_json(json_object: assistant_overrides)
      end
      name = parsed_json["name"]
      session_id = parsed_json["sessionId"]
      if parsed_json["input"].nil?
        input = nil
      else
        input = parsed_json["input"].to_json
        input = Vapi::ChatInput.from_json(json_object: input)
      end
      stream = parsed_json["stream"]
      previous_chat_id = parsed_json["previousChatId"]
      id = parsed_json["id"]
      org_id = parsed_json["orgId"]
      messages = parsed_json["messages"]&.map do |item|
        item = item.to_json
        Vapi::ChatMessagesItem.from_json(json_object: item)
      end
      output = parsed_json["output"]&.map do |item|
        item = item.to_json
        Vapi::ChatOutputItem.from_json(json_object: item)
      end
      created_at = (DateTime.parse(parsed_json["createdAt"]) unless parsed_json["createdAt"].nil?)
      updated_at = (DateTime.parse(parsed_json["updatedAt"]) unless parsed_json["updatedAt"].nil?)
      costs = parsed_json["costs"]&.map do |item|
        item = item.to_json
        Vapi::ChatCostsItem.from_json(json_object: item)
      end
      cost = parsed_json["cost"]
      new(
        assistant_id: assistant_id,
        assistant: assistant,
        assistant_overrides: assistant_overrides,
        name: name,
        session_id: session_id,
        input: input,
        stream: stream,
        previous_chat_id: previous_chat_id,
        id: id,
        org_id: org_id,
        messages: messages,
        output: output,
        created_at: created_at,
        updated_at: updated_at,
        costs: costs,
        cost: cost,
        additional_properties: struct
      )
    end

    # Serialize an instance of Chat to a JSON object
    #
    # @return [String]
    def to_json(*_args)
      @_field_set&.to_json
    end

    # Leveraged for Union-type generation, validate_raw attempts to parse the given
    #  hash and check each fields type against the current object's property
    #  definitions.
    #
    # @param obj [Object]
    # @return [Void]
    def self.validate_raw(obj:)
      obj.assistant_id&.is_a?(String) != false || raise("Passed value for field obj.assistant_id is not the expected type, validation failed.")
      obj.assistant.nil? || Vapi::CreateAssistantDto.validate_raw(obj: obj.assistant)
      obj.assistant_overrides.nil? || Vapi::AssistantOverrides.validate_raw(obj: obj.assistant_overrides)
      obj.name&.is_a?(String) != false || raise("Passed value for field obj.name is not the expected type, validation failed.")
      obj.session_id&.is_a?(String) != false || raise("Passed value for field obj.session_id is not the expected type, validation failed.")
      obj.input.nil? || Vapi::ChatInput.validate_raw(obj: obj.input)
      obj.stream&.is_a?(Boolean) != false || raise("Passed value for field obj.stream is not the expected type, validation failed.")
      obj.previous_chat_id&.is_a?(String) != false || raise("Passed value for field obj.previous_chat_id is not the expected type, validation failed.")
      obj.id.is_a?(String) != false || raise("Passed value for field obj.id is not the expected type, validation failed.")
      obj.org_id.is_a?(String) != false || raise("Passed value for field obj.org_id is not the expected type, validation failed.")
      obj.messages&.is_a?(Array) != false || raise("Passed value for field obj.messages is not the expected type, validation failed.")
      obj.output&.is_a?(Array) != false || raise("Passed value for field obj.output is not the expected type, validation failed.")
      obj.created_at.is_a?(DateTime) != false || raise("Passed value for field obj.created_at is not the expected type, validation failed.")
      obj.updated_at.is_a?(DateTime) != false || raise("Passed value for field obj.updated_at is not the expected type, validation failed.")
      obj.costs&.is_a?(Array) != false || raise("Passed value for field obj.costs is not the expected type, validation failed.")
      obj.cost&.is_a?(Float) != false || raise("Passed value for field obj.cost is not the expected type, validation failed.")
    end
  end
end
