# frozen_string_literal: true

module Vapi
  # This is the provider-specific ID that will be used.
  class DeepgramVoiceId
    ASTERIA = "asteria"
    LUNA = "luna"
    STELLA = "stella"
    ATHENA = "athena"
    HERA = "hera"
    ORION = "orion"
    ARCAS = "arcas"
    PERSEUS = "perseus"
    ANGUS = "angus"
    ORPHEUS = "orpheus"
    HELIOS = "helios"
    ZEUS = "zeus"
    THALIA = "thalia"
    ANDROMEDA = "andromeda"
    HELENA = "helena"
    APOLLO = "apollo"
    ARIES = "aries"
    AMALTHEA = "amalthea"
    ATLAS = "atlas"
    AURORA = "aurora"
    CALLISTA = "callista"
    CORA = "cora"
    CORDELIA = "cordelia"
    DELIA = "delia"
    DRACO = "draco"
    ELECTRA = "electra"
    HARMONIA = "harmonia"
    HERMES = "hermes"
    HYPERION = "hyperion"
    IRIS = "iris"
    JANUS = "janus"
    JUNO = "juno"
    JUPITER = "jupiter"
    MARS = "mars"
    MINERVA = "minerva"
    NEPTUNE = "neptune"
    ODYSSEUS = "odysseus"
    OPHELIA = "ophelia"
    PANDORA = "pandora"
    PHOEBE = "phoebe"
    PLUTO = "pluto"
    SATURN = "saturn"
    SELENE = "selene"
    THEIA = "theia"
    VESTA = "vesta"
    CELESTE = "celeste"
    ESTRELLA = "estrella"
    NESTOR = "nestor"
    SIRIO = "sirio"
    CARINA = "carina"
    ALVARO = "alvaro"
    DIANA = "diana"
    AQUILA = "aquila"
    SELENA = "selena"
    JAVIER = "javier"
  end
end
