# frozen_string_literal: true

require_relative "transfer_assistant_model"
require_relative "transfer_assistant_voice"
require_relative "transfer_assistant_transcriber"
require_relative "transfer_assistant_background_sound"
require_relative "transfer_assistant_first_message_mode"
require "ostruct"
require "json"

module Vapi
  class TransferAssistant
    # @return [String] Optional name for the transfer assistant
    attr_reader :name
    # @return [Vapi::TransferAssistantModel] Model configuration for the transfer assistant
    attr_reader :model
    # @return [Vapi::TransferAssistantVoice] These are the options for the transfer assistant's voice.
    attr_reader :voice
    # @return [Vapi::TransferAssistantTranscriber] These are the options for the transfer assistant's transcriber.
    attr_reader :transcriber
    # @return [String] This is the first message that the transfer assistant will say.
    #  This can also be a URL to a custom audio file.
    #  If unspecified, assistant will wait for user to speak and use the model to
    #  respond once they speak.
    attr_reader :first_message
    # @return [Vapi::TransferAssistantBackgroundSound] This is the background sound in the transfer assistant call. Default for phone
    #  calls is 'office' and default for web calls is 'off'.
    #  You can also provide a custom sound by providing a URL to an audio file.
    attr_reader :background_sound
    # @return [Vapi::TransferAssistantFirstMessageMode] This is the mode for the first message. Default is 'assistant-speaks-first'.
    #  Use:
    #  - 'assistant-speaks-first' to have the assistant speak first.
    #  - 'assistant-waits-for-user' to have the assistant wait for the user to speak
    #  first.
    #  - 'assistant-speaks-first-with-model-generated-message' to have the assistant
    #  speak first with a message generated by the model based on the conversation
    #  state.
    #  @default 'assistant-speaks-first'
    attr_reader :first_message_mode
    # @return [Float] This is the maximum duration in seconds for the transfer assistant conversation.
    #  After this time, the transfer will be cancelled automatically.
    #  @default 120
    attr_reader :max_duration_seconds
    # @return [Float] This is the number of seconds of silence to wait before ending the call.
    #  Defaults to 30.
    #  @default 30
    attr_reader :silence_timeout_seconds
    # @return [OpenStruct] Additional properties unmapped to the current class definition
    attr_reader :additional_properties
    # @return [Object]
    attr_reader :_field_set
    protected :_field_set

    OMIT = Object.new

    # @param name [String] Optional name for the transfer assistant
    # @param model [Vapi::TransferAssistantModel] Model configuration for the transfer assistant
    # @param voice [Vapi::TransferAssistantVoice] These are the options for the transfer assistant's voice.
    # @param transcriber [Vapi::TransferAssistantTranscriber] These are the options for the transfer assistant's transcriber.
    # @param first_message [String] This is the first message that the transfer assistant will say.
    #  This can also be a URL to a custom audio file.
    #  If unspecified, assistant will wait for user to speak and use the model to
    #  respond once they speak.
    # @param background_sound [Vapi::TransferAssistantBackgroundSound] This is the background sound in the transfer assistant call. Default for phone
    #  calls is 'office' and default for web calls is 'off'.
    #  You can also provide a custom sound by providing a URL to an audio file.
    # @param first_message_mode [Vapi::TransferAssistantFirstMessageMode] This is the mode for the first message. Default is 'assistant-speaks-first'.
    #  Use:
    #  - 'assistant-speaks-first' to have the assistant speak first.
    #  - 'assistant-waits-for-user' to have the assistant wait for the user to speak
    #  first.
    #  - 'assistant-speaks-first-with-model-generated-message' to have the assistant
    #  speak first with a message generated by the model based on the conversation
    #  state.
    #  @default 'assistant-speaks-first'
    # @param max_duration_seconds [Float] This is the maximum duration in seconds for the transfer assistant conversation.
    #  After this time, the transfer will be cancelled automatically.
    #  @default 120
    # @param silence_timeout_seconds [Float] This is the number of seconds of silence to wait before ending the call.
    #  Defaults to 30.
    #  @default 30
    # @param additional_properties [OpenStruct] Additional properties unmapped to the current class definition
    # @return [Vapi::TransferAssistant]
    def initialize(model:, name: OMIT, voice: OMIT, transcriber: OMIT, first_message: OMIT, background_sound: OMIT,
                   first_message_mode: OMIT, max_duration_seconds: OMIT, silence_timeout_seconds: OMIT, additional_properties: nil)
      @name = name if name != OMIT
      @model = model
      @voice = voice if voice != OMIT
      @transcriber = transcriber if transcriber != OMIT
      @first_message = first_message if first_message != OMIT
      @background_sound = background_sound if background_sound != OMIT
      @first_message_mode = first_message_mode if first_message_mode != OMIT
      @max_duration_seconds = max_duration_seconds if max_duration_seconds != OMIT
      @silence_timeout_seconds = silence_timeout_seconds if silence_timeout_seconds != OMIT
      @additional_properties = additional_properties
      @_field_set = {
        "name": name,
        "model": model,
        "voice": voice,
        "transcriber": transcriber,
        "firstMessage": first_message,
        "backgroundSound": background_sound,
        "firstMessageMode": first_message_mode,
        "maxDurationSeconds": max_duration_seconds,
        "silenceTimeoutSeconds": silence_timeout_seconds
      }.reject do |_k, v|
        v == OMIT
      end
    end

    # Deserialize a JSON object to an instance of TransferAssistant
    #
    # @param json_object [String]
    # @return [Vapi::TransferAssistant]
    def self.from_json(json_object:)
      struct = JSON.parse(json_object, object_class: OpenStruct)
      parsed_json = JSON.parse(json_object)
      name = parsed_json["name"]
      if parsed_json["model"].nil?
        model = nil
      else
        model = parsed_json["model"].to_json
        model = Vapi::TransferAssistantModel.from_json(json_object: model)
      end
      if parsed_json["voice"].nil?
        voice = nil
      else
        voice = parsed_json["voice"].to_json
        voice = Vapi::TransferAssistantVoice.from_json(json_object: voice)
      end
      if parsed_json["transcriber"].nil?
        transcriber = nil
      else
        transcriber = parsed_json["transcriber"].to_json
        transcriber = Vapi::TransferAssistantTranscriber.from_json(json_object: transcriber)
      end
      first_message = parsed_json["firstMessage"]
      if parsed_json["backgroundSound"].nil?
        background_sound = nil
      else
        background_sound = parsed_json["backgroundSound"].to_json
        background_sound = Vapi::TransferAssistantBackgroundSound.from_json(json_object: background_sound)
      end
      first_message_mode = parsed_json["firstMessageMode"]
      max_duration_seconds = parsed_json["maxDurationSeconds"]
      silence_timeout_seconds = parsed_json["silenceTimeoutSeconds"]
      new(
        name: name,
        model: model,
        voice: voice,
        transcriber: transcriber,
        first_message: first_message,
        background_sound: background_sound,
        first_message_mode: first_message_mode,
        max_duration_seconds: max_duration_seconds,
        silence_timeout_seconds: silence_timeout_seconds,
        additional_properties: struct
      )
    end

    # Serialize an instance of TransferAssistant to a JSON object
    #
    # @return [String]
    def to_json(*_args)
      @_field_set&.to_json
    end

    # Leveraged for Union-type generation, validate_raw attempts to parse the given
    #  hash and check each fields type against the current object's property
    #  definitions.
    #
    # @param obj [Object]
    # @return [Void]
    def self.validate_raw(obj:)
      obj.name&.is_a?(String) != false || raise("Passed value for field obj.name is not the expected type, validation failed.")
      Vapi::TransferAssistantModel.validate_raw(obj: obj.model)
      obj.voice.nil? || Vapi::TransferAssistantVoice.validate_raw(obj: obj.voice)
      obj.transcriber.nil? || Vapi::TransferAssistantTranscriber.validate_raw(obj: obj.transcriber)
      obj.first_message&.is_a?(String) != false || raise("Passed value for field obj.first_message is not the expected type, validation failed.")
      obj.background_sound.nil? || Vapi::TransferAssistantBackgroundSound.validate_raw(obj: obj.background_sound)
      obj.first_message_mode&.is_a?(Vapi::TransferAssistantFirstMessageMode) != false || raise("Passed value for field obj.first_message_mode is not the expected type, validation failed.")
      obj.max_duration_seconds&.is_a?(Float) != false || raise("Passed value for field obj.max_duration_seconds is not the expected type, validation failed.")
      obj.silence_timeout_seconds&.is_a?(Float) != false || raise("Passed value for field obj.silence_timeout_seconds is not the expected type, validation failed.")
    end
  end
end
